name: jana
description: A Discord bot
version: 2.0.1
homepage: https://github.com/chrissxMedia/jana

environment:
  sdk: ^3.0.0

executables:
  jana: jana

dependencies:
  logging: ^1.2.0
  mutex: ^3.0.0
  nyxx: ^6.0.0
  nyxx_extensions: ^4.0.0
  nyxx_lavalink: ^4.0.0-dev.1
  prometheus_client: ^1.0.0
  prometheus_client_shelf: ^1.0.0
  shelf: ^1.3.0
  youtube_explode_dart: ^3.0.0
  youtube_poll: ^0.2.2

dev_dependencies:
  lints: ^6.0.0
